name: Lab 4 CI Pipeline

on:
  # push to the main branch
  push:
    branches:
    - main
  
  # pull request targeting on main branch
  pull_request:
    branches:
    - main


  jobs:
  # start with "lint" job
    lint:
      runs-on: ubuntu-latest
      steps:
        # checkout the repo
        - uses: actions/checkout@v3

        # install Node
        - name: Use Node.js 18.x
          uses: actions/setup-node@v3
          with:
            node-version: "18"

        # Install npm deps
        - name: Install dependencies
          run: npm clean-install

        # Run our linter
        - name: Run linter
          run: npm run lint
